name: Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Checkup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # Install
      - run: npm install -g @angular/cli
      - run: npm install
      # Build
      - run: ng build --prod
      - run: git add .
      - run: |
          git config --global user.name 'admin'
          git config --global user.email 'admin@cenhu.com'
          git commit -am "Automated build report G-011"
          git push
