name: Eslint on Project

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # Run ESLint
      - uses: eslint/github-action@v0
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # Run ESLint
      - run: npm run-script build
